#!/bin/bash
#By Qidong Xia 2026.8.8

mem_G=24
mem_O=2500
nprocs=12
sed -i "39c omp: $nprocs" censorc_ANNPRA13
sed -i "2c %MaxCore $mem_O" ~/.censo_assets/censo_orca_editable.dat

#Read user's information
python askinfo.py
outputpath=$(sed -n "1p" info.txt)
zipname=$(sed -n "2p" info.txt)
email=$(sed -n "3p" info.txt)
rm info.txt
if [ -z "$outputpath" ] || [ -z "$zipname" ] || [ -z "$email" ]
then
  echo "Incomplete Information!"
  exit
fi

#Read the maxthreads
while :
do
  read -r -p "Choose the Maxthreads (1/2/3):" maxthreads
  if [ "$maxthreads" != 1 ] && [ "$maxthreads" != 2 ] && [ "$maxthreads" != 3 ]
  then
    echo "Invalid Input!"
  else
    sed -i "38c maxthreads: $maxthreads" censorc_ANNPRA13
    break
  fi
done

starttime=$(date)

#Input file: .xyz files in current directory
nfile=$(find ./*.xyz|wc -l)
icc=0
for inf in *.xyz
do
  ((icc++))
  echo Running "$inf" ... \("$icc" of "$nfile"\)
#Conformational search by CREST
#Sampling level: GFNFF
#Optimization level: GFN2 (threshold: 6 kcal/mol)
  mkdir "${inf%.xyz}"_search
  cp "$inf" "${inf%.xyz}"_search
  cd "${inf%.xyz}"_search || exit
  crest "$inf" --gfnff
  crest --screen crest_conformers.xyz --gfn2
  cd ../
#Conformational screening by CENSO
#Level: r2scan-3c
  mkdir "${inf%.xyz}"_screening
  cp "$inf" "${inf%.xyz}"_screening
  cp "${inf%.xyz}"_search/crest_ensemble.xyz "${inf%.xyz}"_screening/input_ensemble.xyz
  cd "${inf%.xyz}"_screening || exit
  censo -inp input_ensemble.xyz -inprc ../censorc_ANNPRA13
  crest "$inf" --cregen enso_ensemble_part1.xyz
  cd ../
#Geometry optimization
#Level: HF/3-21G
  ngeom=$(sed -n '$=' "${inf%.xyz}"_screening/crest.energies)
  nbatch=$maxthreads
  if [ "$ngeom" -lt "$maxthreads" ]
  then
    sed -i "1c %mem=$(("$mem_G" * "$maxthreads" / "$ngeom"))GB" template*.gjf
    sed -i "2c %nprocs=$(("$nprocs" * "$maxthreads" / "$ngeom"))" template*.gjf
    nbatch=$ngeom
  else
    sed -i "1c %mem=${mem_G}GB" template*.gjf
    sed -i "2c %nprocs=$nprocs" template*.gjf
  fi
  mkdir "${inf%.xyz}"_batch
  cp "${inf%.xyz}"_screening/crest_ensemble.xyz "${inf%.xyz}"_batch/traj.xyz
  cp template.gjf "${inf%.xyz}"_batch
  cp template2.gjf "${inf%.xyz}"_batch
  cp settings.ini "${inf%.xyz}"_batch
  ntask=$(("$ngeom" / "$nbatch"))
  nmod=$(("$ngeom" % "$nbatch"))
  x=1
  startn=1
  while [ $x -le "$nbatch" ]
  do
    cp -r "${inf%.xyz}"_batch "${inf%.xyz}"_batch_$x
    echo "molclus > molclus_$x.log
echo optimization_batch_$x has finished" >> "${inf%.xyz}"_batch_$x/run.sh
    chmod +x "${inf%.xyz}"_batch_$x/run.sh
    if [ "$x" -le "$nmod" ]
    then
      endn=$(("$startn" + "$ntask"))
    else
      endn=$(("$startn" + "$ntask" - 1))
    fi
    sed -i "2c \ \ ngeom=\ $startn-$endn" "${inf%.xyz}"_batch_$x/settings.ini
    startn=$(("$endn" + 1))
    ((x++))
  done
  echo -e "Running optimization ... \e[33mPLEASE DO NOT CLOSE THE TERMINATION!!!\e[0m"
  for i in "${inf%.xyz}"_batch_*
  do
    cd "$i" || exit
    ./run.sh &
    cd ../
  done
  wait
  cd "${inf%.xyz}"_batch || exit
  mkdir opt
  mv traj.xyz opt
  rm template*
  rm settings.ini
  cd ../
  for i in "${inf%.xyz}"_batch_*
  do
    cd "$i" || exit
    cat isomers.xyz >> ../"${inf%.xyz}"_batch/opt/isomers.xyz
    mv gau*.out ../"${inf%.xyz}"_batch/opt
    mv ./*.log ../"${inf%.xyz}"_batch/opt
    cd ../
    rm -r "$i"
  done
  cd "${inf%.xyz}"_batch/opt || exit
  echo -e "\n\n\n" | isostat
  ngeom=$(grep -c " Energy =" cluster.xyz)
  cd ../../
#NMR calculation
#Level: mPW1PW91/6-31G(d)
  nbatch=$maxthreads
  if [ "$ngeom" -lt "$maxthreads" ]
  then
    sed -i "1c %mem=$(("$mem_G" * "$maxthreads" / "$ngeom"))GB" template*.gjf
    sed -i "2c %nprocs=$(("$nprocs" * "$maxthreads" / "$ngeom"))" template*.gjf
    nbatch=$ngeom
  else
    sed -i "1c %mem=${mem_G}GB" template*.gjf
    sed -i "2c %nprocs=$nprocs" template*.gjf
  fi
  cp template_nmr.gjf "${inf%.xyz}"_batch/opt/template.gjf
  ntask=$(("$ngeom" / "$nbatch"))
  nmod=$(("$ngeom" % "$nbatch"))
  x=1
  startn=1
  while [ $x -le "$nbatch" ]
  do
    mkdir "${inf%.xyz}"_batch_$x
    cp nmr_calc.sh "${inf%.xyz}"_batch_$x
    if [ "$x" -le "$nmod" ]
    then
      endn=$(("$startn" + "$ntask"))
    else
      endn=$(("$startn" + "$ntask" - 1))
    fi
    cd "${inf%.xyz}"_batch/opt || exit
    echo -e "2\ncluster.xyz\n$startn-$endn\nnmr\n" | xyz2QC
    mv nmr*.gjf ../../"${inf%.xyz}"_batch_$x
    cd ../../
    startn=$(("$endn" + 1))
    ((x++))
  done
  rm "${inf%.xyz}"_batch/opt/template.gjf
  for i in "${inf%.xyz}"_batch_*
  do
    cd "$i" || exit
    ./nmr_calc.sh &
    cd ../
  done
  wait
  cd "${inf%.xyz}"_batch || exit
  mkdir nmr
  cd ../
  for i in "${inf%.xyz}"_batch_*
  do
    cd "$i" || exit
    mv nmr*.out ../"${inf%.xyz}"_batch/nmr
    mv nmr*.gjf ../"${inf%.xyz}"_batch/nmr
    cd ../
    rm -r "$i"
  done
#Data processing
  mkdir "${inf%.xyz}"_result
  cd "${inf%.xyz}"_batch/nmr || exit
  for j in *.out
  do
    echo "$j" >> iso_summary.txt
    grep 'C    Isotropic =' "$j" >> iso_summary.txt
    grep 'E(' "$j" >> E_summary.txt
  done
  mv iso_summary.txt ../../"${inf%.xyz}"_result
  mv E_summary.txt ../../"${inf%.xyz}"_result/E_summary.txt
  cp ../../Caverage_E.py ../../"${inf%.xyz}"_result
  cd ../../"${inf%.xyz}"_result || exit
  python Caverage_E.py
  rm Caverage_E.py
  mv iso_summary.txt "${inf%.xyz}"_iso_summary.txt
  mv E_summary.txt "${inf%.xyz}"_E_summary.txt
  mv result.txt "${inf%.xyz}"_result.txt
  cd ../
  echo -e "\e[33m$inf has finished\e[0m"
done

endtime=$(date)

#Package the input and output files and send a reminder email
for inf in *.xyz
do
  zip -m "$zipname".zip "$inf"
  zip -r -m "$zipname".zip "${inf%.xyz}"_*
done
mv "$zipname".zip "$outputpath"
echo "Subject: ANN-PRA(2013) Calculation Done!

The calculation task has been completed, and the output file $zipname.zip has been stored in the directory $outputpath.
Used time: from $starttime to $endtime" >> mail.txt
ssmtp "$email" < mail.txt
rm mail.txt
echo -e "\e[33m---------------------CALCULATION DONE---------------------\e[0m"